---

- name: Prepare machines for cluster
  hosts: kube-cluster
  roles: 
    - { role: prepare-nodes }

- name: Master setup
  hosts: kube-master
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  roles: 
    - { role: master }

- name: Node setup
  hosts: kube-node
  roles: 
    - { role: worker }

# - name: check
#   hosts: kube-master
#   tasks:
#     - debug:
#         # var: hostvars[inventory_hostname]
#         msg: "ip: {{hostvars[inventory_hostname]['ip']}}"

