---

- name: Prepare machines for cluster
  hosts: kube-cluster
  roles: 
    - { role: prepare-nodes }

- name: Master setup
  hosts: kube-master
  roles: 
    - { role: master }

- name: Node setup
  hosts: kube-node
  roles: 
    - { role: worker }


