---

- name: Check if master setup exists
  hosts: kube-master
  tasks:
    - stat:
        path: /etc/kubernetes/admin.conf
      register: master_config

- name: Check if helm exists
  hosts: kube-master
  tasks:
    - stat:
        path: /usr/local/bin/helm
      register: helm_result

- name: Reset Tiller & Helm
  hosts: kube-master
  tasks:
    - command: helm reset
      when: helm_result.stat.exists
    - file:
        path: /usr/local/bin/helm
        state: absent
      when: helm_result.stat.exists

- name: Drain and delete all nodes in cluster
  hosts: kube-master
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  tasks:
    - command: "kubectl drain {{ item }} --delete-local-data --force --ignore-daemonsets"
      with_items: "{{ groups['kube-cluster'] }}"
      when: master_config.stat.exists
      ignore_errors: true
    - command: "kubectl delete node {{ item }}"
      with_items: "{{ groups['kube-cluster'] }}"
      when: master_config.stat.exists
      ignore_errors: true
    
- name: Reset kubeadm
  hosts: kube-cluster
  roles: 
    - { role: reset }