---

- name: Generate token & print join command
  command: "kubeadm token create --print-join-command"
  register: join_command_with_token
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Join to cluster
  command: "{{ join_command_with_token.stdout }}"
